### ISSUE TITLE
nix_hci adapter: uninitialized file descriptor with Python 2

### ISSUE THREAD

**Issue by mwiercinski** [ttu/ruuvitag-sensor#108]
DEVNULL is only initialized with Python 3. In case of the old version it attempts to reference uninitialized variable.

https://github.com/ttu/ruuvitag-sensor/blob/b7d2fc2909546935962798445e03b049abd1d256/ruuvitag_sensor/adapters/nix_hci.py#L30

**Comment by ttu** [comment]
Thanks for the issue! 

Apparently check had broken during some refactoring. Changed it back to original.

This time also executed verification test with Python 2, so should work. Will release a fixed version soon.
