### ISSUE TITLE
How do I update my tag to a different data type?

### ISSUE THREAD

**Issue by yudhiesh** [ttu/ruuvitag-sensor#114]
I am trying to identify the sensors near me but I am getting the following error 

```
DATA TYPE 2 IS OBSOLETE. UPDATE YOUR TAG
```
Even though I am using the latest version of 2.5.9.

**Comment by precabal** [comment]
same here. getting the same message after updating to 3.28.13

**Comment by ttu** [comment]
Hi!

Check the guide how to change data mode from RuuviTag-site: https://lab.ruuvi.com/dfu/

Should be like this:
`The firmware boots up first time in the mode 1. Button "B" changes the mode to 2. On button presses, the modes cycle 1 -> 2 -> 3 -> 1 -> 2 -> 3 -> 1...`

**Comment by ttu** [comment]
Hi @MrGeCode ! Can you enable debug logging (https://github.com/ttu/ruuvitag-sensor#log-all-events-to-log-file) and send me lines before the warning message (`DATA TYPE x IS OBSOLETE. UPDATE YOUR TAG`). There should be something starting with `"Parsing advertisement data:`. Thanks!
