### ISSUE TITLE
Examples lack entrypoint protection for multiprocessing

### ISSUE THREAD

**Issue by dronir** [ttu/ruuvitag-sensor#123]
**Describe the bug**
In most of the examples, the call to `RuuviTagSensor.get_datas` fails. The fix is simple and suggested by the error message, since this is a common issue with `multiprocessing`. This applies to Windows as well as macOS.

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - ruuvitag_sensor package version: 1.1.0 (4c58228)
 - RuuviTag firmware version: whatever was prodution in early March 2021
 - Data format: 5
 - Bleson
 - Python: 3.9.2
 
**Reproducing**

Running most of the examples just on the command line, the code crashes with a bunch of exceptions on the `get_datas` call. The relevant part of the exception dump is:

```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

Simply adding the `if __name__ == '__main__':` around the relevant part fixes this crash entirely. In most of the simple examples it's just the single line with the `get_datas` call.

The underlying reason for this is that on Windows and macOS, `multiprocessing` uses the `spawn` method to start a new process, while on Linux it uses `fork`. The [programming guidelines](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods) for the package say:

>Make sure that the main module can be safely imported by a new Python interpreter without causing unintended side effects (such a starting a new process).
>…one should protect the “entry point” of the program by using `if __name__ == '__main__':`

**Comment by ttu** [comment]
Thanks for the bug report! 

We should change all examples 👍 I'll add help wanted tag.

**Comment by dronir** [comment]
I think I'll try to do some soon, while I'm still working on my own code, at least for the examples I can easily try out.

**Comment by ttu** [comment]
@dronir great! All commits are appreciated :)
