### ISSUE TITLE
Configure the HCITool to use passive scanning

### ISSUE THREAD

**Issue by ttu** [ttu/ruuvitag-sensor#128]
Configure the HCITool to use passive scanning which does not request for scan responses. This saves a little bit of battery on the tags.

```
hcitool lescan --duplicates --passive on HCITool.
```

https://github.com/ttu/ruuvitag-sensor/issues/122#issuecomment-826698177v

**Comment by ypid** [comment]
#140 has been merged which implements this. This issue is already linked but was not closed automatically. It can be closed in my eyes.
