### ISSUE TITLE
hcitool/hciconfig deprecated in upstream bluez

### ISSUE THREAD

**Issue by Paippi** [ttu/ruuvitag-sensor#129]
Hey,

Tried using this tool but I kept getting errors about hciconfig missing. Looked a bit into it. It seems to be deprecated.
https://github.com/chrippa/ds4drv/issues/123
https://wiki.archlinux.org/title/Bluetooth

> Some tools such as hcitool and hciconfig have been deprecated upstream, and are no longer included in bluez-utils. Since these tools will no longer be updated, it is recommended that scripts be updated to avoid using them. If you still desire to use them, install bluez-utils-compatAUR. See FS#53110 and the Bluez mailing list for more information.

As it seems these tools are not maintained anymore could they be replaced with something that is maintained?

**Solution for other Arch users**

install bluez-utils-compat package from AUR

Environment (please complete the following information):

* OS: Arch Linux (5.12.5-arch1-1)
* ruuvitag_sensor 1.2.0

**Comment by ttu** [comment]
Thanks for the issue and for the solution for Arch users 👍 

There is a mention about deprecation in the README. I will link this to original issue, so Arch solution can be found later https://github.com/ttu/ruuvitag-sensor/issues/31
