### ISSUE TITLE
Updated install instructions ffor Rasperry Pi

### ISSUE THREAD

**Issue by bkosk** [ttu/ruuvitag-sensor#135]
I was having trouble with the Ruuvi Tag sensor package working on my Raspberry Pi following these instructions (https://github.com/ttu/ruuvitag-sensor/blob/master/install_guide_pi.md). I was unable to replicate the traceback at the help line. After communicating with Ruuvi, the following command should be used:

`$ python3 -m pip install --user ruuvitag_sensor`
`$ python3 -m ruuvitag_sensor -h`

And then the rest of the install guide should follow.

**Comment by ttu** [comment]
Thanks for the issue 👍 

Would you like to make required fixes to the guide?
