### ISSUE TITLE
Battery level

### ISSUE THREAD

**Issue by mikaelho** [ttu/ruuvitag-sensor#14]
Could we get the battery level (voltage) as well?

**Comment by ttu** [comment]
Battery voltage is supported in Data Format 3
https://github.com/ruuvi/ruuvi-sensor-protocols
https://github.com/ttu/ruuvitag-sensor/blob/master/ruuvitag_sensor/decoder.py#L141

**Comment by mikaelho** [comment]
Thanks!

I was not getting the battery value, but finally found the rather random mention in the forums that you have to press the B button to change modes from 'weather station' to 'sensor tag' to get to format 3.
