### ISSUE TITLE
Can't get device info: No such device

### ISSUE THREAD

**Issue by bbruhn-aedifion** [ttu/ruuvitag-sensor#142]
**Describe the bug**

The samples [find_sensors](https://github.com/ttu/ruuvitag-sensor#find-sensors) and [get_data_for_sensors](https://github.com/ttu/ruuvitag-sensor#get-data-for-specified-sensors) result in the error in the title. 

```
Finding RuuviTags. Stop with Ctrl+C.
Start receiving broadcasts (device hci0)
FYI: Calling a process with sudo: hciconfig hci0 reset
Can't get device info: No such device
Problem with hciconfig reset. Retry reset.
...
```

Using the regular `hcitool lescan` works fine and the RuuviTag is discovered:

```
sudo hcitool lescan

LE Scan ...
D4:22:5B:5B:98:C2 (unknown)
D4:22:5B:5B:98:C2 Ruuvi 98C2
37:2D:59:53:25:BD (unknown)
7A:90:D0:D9:0C:6A (unknown)
```

Looking for this specific RuuviTag via this module also fails

```
from ruuvitag_sensor.ruuvitag import RuuviTag

sensor = RuuviTag("D4:22:5B:5B:98:C2")

# update state from the device
state = sensor.update()

# get latest state (does not get it from the device)
state = sensor.state

print(state)
```

```
Can't get device info: No such device
Can't get device info: No such device
```

**Environment (please complete the following information):**
 - OS: Ubuntu, 20.04.3 LTS (Focal Fossa)
 - ruuvitag_sensor package version: 1.2.0
 - RuuviTag firmware version: 3.30.2
 - Data format: 5

**Comment by ttu** [comment]
Hi!

Sorry that didn't get back to your issue on time.  Did you find solution on this issue?

We had few error cases listed in https://github.com/ttu/ruuvitag-sensor/blob/master/developer_notes.md#error-cases. Maybe some of those could have helped?

If you found a solution could you add it here or update the notes and do a PR?

Sorry once again for ignoring this issue :( Please reopen this if you have any further questions.
