### ISSUE TITLE
Fails to list or connect to Ruuvitags

### ISSUE THREAD

**Issue by rlaitner** [ttu/ruuvitag-sensor#17]
Hi,
I have a ruuvitag broadcasing about 10 feet from my pi; however, I can't connect to it. I get an error that says "set scan parameters failed: Input/Output error" when I run `python ruuvitag_sensor -f` from command line. Am I missing something obvious? It also appears in a third-party application known as Ruuvitag-logger that uses this as a dependency.

**Comment by ttu** [comment]
Can you send me what you have in ruuvitag_sensor.log file? Here are few commands that we can use for troubleshooting.

What is the device when you type?
```sh
$ hcitool dev
```
Command should print something like this:
```
Devices:
        hci0    XX:XX:XX:XX:XX:XX
```
Does this command start to print MAC addresses?
```sh
$ hcitool lescan
```

**Comment by rlaitner** [comment]
I didn't the log file originally. I figured it out. My pi had psutil installed for python 2.x, but not python 3.x. Thanks for your help. It works now.

**Comment by ttu** [comment]
Good that you got it working 👍 

Will try to add soon some troubleshooting documentation that will cover most common error cases.
