### ISSUE TITLE
Add tests for find_ruuvitags_async

### ISSUE THREAD

**Issue by ttu** [ttu/ruuvitag-sensor#183]
`find_ruuvitags_async` doesn't have any tests.
https://github.com/ttu/ruuvitag-sensor/blob/c0d22b2a789e873b3d208a350d9aa12702901718/ruuvitag_sensor/ruuvi.py#L111

Add test to https://github.com/ttu/ruuvitag-sensor/blob/master/tests/test_ruuvitag_sensor_async.py

NOTE: Remove `pytest.mark.skip` from test file to execute the tests and Bleak must be installed manually https://github.com/ttu/ruuvitag-sensor#bleak

**Comment by dhruvshettty** [comment]
Hi, is anyone working on this issue? I will pick it up if not
