### ISSUE TITLE
Docs request: Pull Request Templates

### ISSUE THREAD

**Issue by dhruvshettty** [ttu/ruuvitag-sensor#189]
PR templates would make contributions to this project much easier if there was a checklist that contributors can follow. This also avoids repeated questions from the project maintainers. For example, asking if all test cases are covered, if there are any core changes, etc. A sample template below borrowed from [Axolo](https://axolo.co/blog/p/part-3-github-pull-request-template).

Additionally, this would also help with better commit messages if we use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) in this project. During the squash workflow, the PR can come with a [default message tag](https://www.conventionalcommits.org/en/v1.0.0/#do-all-my-contributors-need-to-use-the-conventional-commits-specification).

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Describe your changes below
Please include a summary of the changes and the related issue.

## Checklist before requesting a review
- [ ] Self-review of my code
- [ ] Commented my code, particularly in hard-to-understand areas
- [ ] If core feature, added thorough tests.
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

**Comment by ttu** [comment]
This is a good idea. I would make small changes, e.g. to the checklist. Most important are that code follows current style,  documentation is updated and tests are added and are still working.

## Description

Please include a summary of the changes and the related issue.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update


## Checklist

- [ ] My code follows the coding style used in this project
- [ ] Commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Conventionalcommits is pretty interseting and in some projects it might force to follow good practices. 

So far I have had an approach that commit messages should be clear enough that developers have an idea what commit contains (no commits with just fix etc.)

CHANGELOG contains only small part of changes. Mainly changes that might interest package users or is something breaks they might see from CHANGELOG what might have caused it.

I have been using SemVer with releases. E.g. released a new major version when dropped Python2 support. Minor releases include new functionality and patches are bug fixes.

Picking something from conventionalcommits is, that I could start to add <type> to each merge commit, as it will make commit history even more clear.
