### ISSUE TITLE
Negative values not decoded correctly from data format3

### ISSUE THREAD

**Issue by ssamppa** [ttu/ruuvitag-sensor#20]
Negative values seems to be incorrectly decoded. Last night was the first night with subzero temperatures at our home, see the picture. Crossing zero leads ruuvitag_sensor 0.8.0 to report -128.
Ideally add a test case for these boundary values :)

![img_3464](https://user-images.githubusercontent.com/6480819/30045481-5378abd2-920d-11e7-9e43-5552fcb9b6ee.JPG)

**Comment by ttu** [comment]
Thanks for the info!

Unfortunately haven't been using much RuuviTag's data format 3, as my own home automation project hasn't been active in a while, so I haven't validated all different data cases.

Found a fix for the integer part of the temperature and still need to fix fractional part when I get more info of what the firmware will actually send (not sure if there is an error in decoding).

**Comment by ssamppa** [comment]
Seems to be working fine now. Thanks for the quick fix!
![img_3465](https://user-images.githubusercontent.com/6480819/30096240-03ac4b08-92e0-11e7-9a2d-e55e7915bd89.JPG)

**Comment by ttu** [comment]
https://github.com/ttu/ruuvitag-sensor/commit/e6f2f40e535df29487ce5ccbc264e5c4d64fa505
