### ISSUE TITLE
pi username should not be in command

### ISSUE THREAD

**Issue by DG12** [ttu/ruuvitag-sensor#25]
I logged in as dgerman
so /home/pi  in the following examples

$ python3 /home/pi/.local/lib/python3.4/site-packages/ruuvitag_sensor -h

should probably be
 
$ python3 **~**/.local/lib/python3.4/site-packages/ruuvitag_sensor -h
 
Great install instructions. 
Great package!!  THANK YOU!

**Comment by ttu** [comment]
Hi,

That is a good point, that it is better to use `~` for the home directory, instead of `/home/pi`, even though guide was made with pi user.

Do you want to make the change? You could also fix typos etc. if you see some :)

**Comment by ttu** [comment]
Fixed in commit: https://github.com/ttu/ruuvitag-sensor/commit/8e64469147a813f4cb1a630d496548e0b8f97053
