### ISSUE TITLE
Update InfluxDB examples to match RuuviCollector's naming conventions 

### ISSUE THREAD

**Issue by ttu** [ttu/ruuvitag-sensor#30]
Update datamodels for InfulxDB from examples:
https://github.com/ttu/ruuvitag-sensor/blob/master/examples/post_to_influxdb.py https://github.com/ttu/ruuvitag-sensor/blob/master/examples/post_to_influxdb_rx.py

To match model from:
https://github.com/Scrin/RuuviCollector/blob/format5-beta/src/main/java/fi/tkgwf/ruuvi/bean/RuuviMeasurement.java

**Comment by ttu** [comment]
Good. Thanks!

**Comment by ttu** [comment]
@ojousima I will label this back as help wanted (for hacktoberfest)

**Comment by ojousima** [comment]
Sorry, I had forgotten this completely. I'll take a look

**Comment by ttu** [comment]
Closed with https://github.com/ttu/ruuvitag-sensor/commit/d71e1c43b6667eb07422de0add277159081f47cf
