### ISSUE TITLE
hcitool and hcidump are not terminated

### ISSUE THREAD

**Issue by samuelphy** [ttu/ruuvitag-sensor#32]
I’ve noticed that when my Python code is executed from rc.local (i.e. at startup) the RuuviTagSensor.get_data_for_sensors() is firing off new processes that are not terminated. I.e. each time RuuviTagSensor.get_data_for_sensors() is called `hcitool lescan` and `hcidump` are executed again and again. This memory leak fills up the RAM… I.e. I get multiple versions of the processes below:
```
pi@raspberry:~ $ ps 2188
PID TTY STAT TIME COMMAND
2188 ? S 0:00 hcitool lescan --duplicates
pi@raspberry:~ $ ps 2231
PID TTY STAT TIME COMMAND
2231 ? S 0:00 sudo -n hcidump --raw
```
Note: This does not happen when I execute the Python code on the command line using nohup, doesn’t matter if the user is pi or root. I guess the error lies in:
`def stop(hcitool, hcidump):`
in ble_communication.py but I have not looked further for now.

**Comment by samuelphy** [comment]
I think I have missed installing `psutil`. I'll verify and close if it fixes the issue.

**Comment by samuelphy** [comment]
psutil was already installed but the error was on my part having the "&" operand at the end of the command line in rc.local.

**Comment by aapris** [comment]
I see the same when I run my script from crontab's @reboot. Finally `hci0` hangs and I get no readings from RuuviTags. This happened twice yesterday on two different Raspi.

This may or may not help (the other Raspi needed reboot):
```
sudo hciconfig hci0 reset
sudo hciconfig hci0 up
```
I've 4 seconds timeout in this command:
`RuuviTagSensor.get_data_for_sensors([], timeout_in_sec)`
Maybe it should be longer?

Here is part of my `ps aux | grep hci`, there were tens of similar rows.

```
root     23519  0.0  0.3   7632  3472 ?        S    05:36   0:00 sudo -n hcitool lescan --duplicates
root     23525  0.0  0.0   2480   668 ?        S    05:36   0:12 hcitool lescan --duplicates
root     23546  0.0  0.3   7632  3412 ?        S    Dec24   0:00 sudo -n hcitool lescan --duplicates
root     23553  0.0  0.0   2480   632 ?        S    Dec24   2:11 hcitool lescan --duplicates
root     25215  0.0  0.3   7632  3360 ?        S    Dec22   0:00 sudo -n hcitool lescan --duplicates
root     25220  0.0  0.0   2480   640 ?        S    Dec22   2:35 hcitool lescan --duplicates
root     25452  0.0  0.3   7632  3356 ?        S    Dec27   0:00 sudo -n hcitool lescan --duplicates
root     25460  0.0  0.0   2480   660 ?        S    Dec27   1:17 hcitool lescan --duplicates
```

**Comment by jareware** [comment]
I'm not detaching with `&` in my `rc.local` but I'm still getting the runaway `hcitool` processes:

![image](https://user-images.githubusercontent.com/560055/49571984-66587b80-f943-11e8-8083-ceb431b5e503.png)

(the drop is a reboot)

```
$ ps aux | grep hcitool | wc -l
149
```

I did notice though that I'm running 0.9.0, not the latest 0.11.0, will update and see if it has any effect.

**Comment by aapris** [comment]
Newest version supports newest Ruuvitag data formats, so if you upgrade firmware, you need not upgrade ruuvitag_sensor also. I've this in root's crontab:
```
58 * * * *	killall hcitool; hciconfig hci0 reset && hciconfig hci0 up
0 * * * *	/usr/bin/supervisorctl restart RuuviTag
```
It kills all runaway hcitool processes and then (after 2 minutes) restarts my reader process.

**Comment by jareware** [comment]
Yeah, I've "solved" this in a similar manner, with a scheduled reboot once per week.

**Comment by jareware** [comment]
![image](https://user-images.githubusercontent.com/560055/49684118-de57aa80-fad7-11e8-939b-3edd426f5653.png)

No effect.

**Comment by aapris** [comment]
Hmm, it seems after upgrading to 0.11.0 my RuuviTag data has a lot of gaps at two separate locations. This happened weeks ago after I upgraded `ruuvitag-sensor` library. This can also be an issue in my hardware (Raspberry pi 3) so I've to investigate more of this to be sure what is the root cause.
![image](https://user-images.githubusercontent.com/310662/49690633-dc740280-fb3c-11e8-92c7-3c3b69444f46.png)

**Comment by aapris** [comment]
Could this be a problem in Raspbian or hcitool? Maybe some upgrade messed this up?

**Comment by oduo** [comment]
I have also this issue. I use ruuvitag-sensor only from ruuvi-hass https://github.com/peltsippi/ruuvi-hass

When running long time I have multiple hcitool lescan --duplicates running on rassberry pi

root     26326  0.0  0.0   2480   624 ?        S    Jan09   0:32 hcitool lescan --duplicates
root     27096  0.0  0.3   7228  3324 ?        S    Jan11   0:00 sudo -n hcitool lescan --duplicates
root     27103  0.0  0.0   2480   668 ?        S    Jan11   0:15 hcitool lescan --duplicates
root     27217  0.0  0.3   7228  3368 ?        S    Jan06   0:00 sudo -n hcitool lescan --duplicates
root     27224  0.0  0.0   2480   668 ?        S    Jan06   0:46 hcitool lescan --duplicates
root     27456  0.0  0.3   7228  3260 ?        S    Jan09   0:00 sudo -n hcitool lescan --duplicates
root     27463  0.0  0.0   2480   668 ?        S    Jan09   0:30 hcitool lescan --duplicates
root     27626  0.0  0.3   7228  3256 ?        S    Jan08   0:00 sudo -n hcitool lescan --duplicates

pip list
ruuvitag-sensor         0.11.0
psutil                  5.4.8

(homeassistant) homeassistant@hassbian:~ $ uptime
 15:59:39 up 28 days, 34 min,  1 user,  load average: 0.02, 0.31, 0.30
(homeassistant) homeassistant@hassbian:~ $ pgrep hcitool|wc -l
116

Something wrong with process killing?

**Comment by sevesalm** [comment]
I was able to solve my similar issues by calling the `stop()` method for the `RuuviTagReactive` object. Please check issue #125 for details.
