### ISSUE TITLE
Add helper functions

### ISSUE THREAD

**Issue by ttu** [ttu/ruuvitag-sensor#33]
* Is Tag present function
  * As a static RuuviTagSensor function
  * As a method in RuuviTag class
* What other functions would be handy?

**Comment by ghsriram** [comment]
Hello. I am using this example line but I still find my code hanging endlessly if the ruuvitag BLE is out of reach from my Pi. Any idea? I simply using stock code from ruuvitag-logger.py. Python version 3.6.
Thanks in advance. 

datas = RuuviTagSensor.get_data_for_sensors(macs, timeout_in_sec)

**Comment by ttu** [comment]
Hi @ghsriram! Can you create a new issue from this BLE error?

Won't make any fixes for BLE communication for this old implementation, but you can try the implemenation with Bleson BLE communication. Check more info from [README](https://github.com/ttu/ruuvitag-sensor#requirements).

**Comment by ghsriram** [comment]
Thanks much. I will try that.
