### ISSUE TITLE
Raspberry Zero W and wireless on Raspbian Stretch

### ISSUE THREAD

**Issue by hacklover** [ttu/ruuvitag-sensor#37]
I followed the guide and everything was working, but when I reboot Zero W for the first time after updates, I can't see it on network. I've reinstalled Raspbian already 4 times trying a lot of different tricks. Reinstalled Raspbian Stretch, reconfigured everything but after reboot, no way to see it on network. It's a fucking waste of patience, I'll buy another Raspberry 3 Model B+.

WHY I can connect to Wi-Fi without setting static IP or other shit before rebooting?

**Comment by samuelphy** [comment]
This does not seem to be related to ruuvitag-sensor at all, but since I'm a nice guy I can give you a tip. Are you having trouble with the Avahi daemon at startup? If so, just download the latest Raspian version and it will fix your problem.

**Comment by hacklover** [comment]
I know that and I'm sorry for the rage, feel free to delete this issue after all... ty for the tip, anyway I'm unable to download it because first I have to fix the static ip / dhcp trouble, but I don't know how. On web I found also other guys having problems with Stretch on Zero W :/

Anyway I can make sure you that the guide and code, before rebooting for the first time, is working good on Raspberry Zero W and isn't your fault

**Comment by ttu** [comment]
@hacklover Hope you got your problems fixed. It is known problem with all IT-systems that these things just don't work, ever. 

Knowing that, raging is pretty understandable. Although Github issue is not the best place for that, no problems.
