### ISSUE TITLE
0.10.0 updating error

### ISSUE THREAD

**Issue by havnjero** [ttu/ruuvitag-sensor#38]
getting an error when updating to 0.10.0

pi@openplotter:~ $ sudo pip install ruuvitag_sensor
Downloading/unpacking ruuvitag-sensor
  Downloading ruuvitag_sensor-0.10.0.tar.gz
  Running setup.py (path:/tmp/pip-build-MPcNsj/ruuvitag-sensor/setup.py) egg_info for package ruuvitag-sensor
    error in ruuvitag_sensor setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in ruuvitag_sensor setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-MPcNsj/ruuvitag-sensor
Storing debug log for failure in /root/.pip/pip.log

**Comment by ttu** [comment]
'install_requires' uses environment markers, which require newer __setuptools__.  Tell me if updating solves this and if not, let's inspect this more.

**Comment by ttu** [comment]
Will close this as expecting that setuptools update fixes the problem. Please reopen if you get same problem again.
