### ISSUE TITLE
Example tag_test.py is wrong — no output

### ISSUE THREAD

**Issue by bevolz** [ttu/ruuvitag-sensor#59]
I had to change the tag_test.py script to get any output. Had to change it to:

Import ruuvitag_sensor
From ruuvitag_sensor.log import log
From ruuvitag_sensor.ruuvi import RuuviTagSensor

ruuvitag_sensor.log.enable_console()

RuuviTagSensor.find_ruuvitags()

(The import & from should be lower case).

**Comment by ttu** [comment]
Hi @bevolz!

Where is this tag_test.py script?

**Comment by bevolz** [comment]
Hi:

It is at https://github.com/ttu/ruuvitag-sensor/blob/master/install_guide_pi.md. Sorry for not including the link.

---
Open nano editor and create test script tag_test.py

$ nano tag_test.py
Add this content. Exit with Ctrl-X and select Y to save

from ruuvitag_sensor.ruuvi import RuuviTagSensor

RuuviTagSensor.find_ruuvitags()
Execute script just created. Expect the same result as from find all tags executed from the command line.

$ python3 tag_test.py
---


  *   Bernie

**Comment by ttu** [comment]
Thanks! Didn't remember that there was an example in the install guide :)

Would you like to fix that and do a PR?

**Comment by bevolz** [comment]
Hi ... OK, will do.

- Bernie

On Nov 22, 2018, at 2:50 PM, Tomi Tuhkanen <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! Didn't remember that there was an example in the install guide :)

Would you like to fix that and do a PR?
