### ISSUE TITLE
Add accelerometer reading

### ISSUE THREAD

**Issue by ssamppa** [ttu/ruuvitag-sensor#6]
Hi

It would be nice to have support for accelerometer values too as specified in the Data Format 3.
Probably also add the battery voltage too.

Thanks

**Comment by ttu** [comment]
Hi,

Implementation of Data Format 3 is still work in progess and it can be found from own branch https://github.com/ttu/ruuvitag-sensor/tree/data-format-3. I still have to check that all datas are decoded correctly.

**Comment by ttu** [comment]
Merged to master (https://github.com/ttu/ruuvitag-sensor/pull/12) and released with version 0.6.0
