### ISSUE TITLE
InfluxDB missing fields

### ISSUE THREAD

**Issue by lausvi** [ttu/ruuvitag-sensor#61]
Hi.

I am using post_to_influxdb.py and it's working otherwise nicely to my needs. However when I do fing_tags I can see the battery values from the RuuviTags, but those are not exported into my InfluxDB. The fields I see there (and can use in my Grafana) are: accelerationX, -Y and -Z, humidity, movementCounter, pressure and temperature.

Using RuuviCollector I can get all those into my InfluxDB, but I'd prefer your Python scripts :)

The tags are brand new, have the default firmware (Weather Station, I believe) and are in the default RAW mode (red led flashing).

**Comment by ojousima** [comment]
Thanks for the report, I'll look into this over the weekend

**Comment by ojousima** [comment]
Sorry for the delay. 
@lausvi can you check #63 out?

**Comment by lausvi** [comment]
No problem!

Just tested it and now it works. Thanks!
