### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by tonipalmgren** [ttu/ruuvitag-sensor#66]
"More samples and simple HTTP server under examples directory."

Clicking "samples" leads to a 404 (https://github.com/ttu/ruuvitag-sensor/blob/master/examples/rx.py). I'm assuming the correct URL is https://github.com/ttu/ruuvitag-sensor/tree/master/examples.

**Comment by ttu** [comment]
@tonipalmgren thanks, correct link should be https://github.com/ttu/ruuvitag-sensor/blob/master/examples/reactive_extensions.py
