### ISSUE TITLE
Calculation of acceleration is not correct

### ISSUE THREAD

**Issue by samuelphy** [ttu/ruuvitag-sensor#8]
According to the Data format 3 specification the acceleration value is a 2-complement int16 MSB first. One way to calculate the signed value is to use this:
```
# Example: twos_complment(0xFC18,16) = -1000
def twos_complement(value, bits):
    if (value & (1 << (bits - 1))) != 0: # Check if sign bit is set
        value = value - (1 << bits)      # Compute negative value
    return value
```

It might also be useful to get the data for each axle separately.

**Comment by ttu** [comment]
Thanks for the example. Currently away from the computer, but will try to make this fix and add all acceleration values by the end of next week. After that could also merge data format 3 branch to master and make a new pypi release.

**Comment by ttu** [comment]
Fixed calculations and added data for each axel (https://github.com/ttu/ruuvitag-sensor/commit/2a060850db3a48e0ce789a148e91a0ad9398d57d)

**Comment by samuelphy** [comment]
Great!
