### ISSUE TITLE
Data format 3 decoding is not working with Python2

### ISSUE THREAD

**Issue by Jussihoo** [ttu/ruuvitag-sensor#9]
There is this line of code in the decoder.py (line 124) which does not work with python2

byte_data = bytes.fromhex(data)

It works when changed as:
byte_data = bytearray.fromhex(data)

I suppose this would work also with python3 so you might want to consider making this change?

Thanks for the great library!

**Comment by ttu** [comment]
Thanks for the change recommendation. Changed byte to bytearray https://github.com/ttu/ruuvitag-sensor/commit/fed8b0ceea84e97d693af5b5c757ba407265b45d

**Comment by ttu** [comment]
Merged to master (https://github.com/ttu/ruuvitag-sensor/pull/12) and released with version 0.6.0
